export type GraphCategory = '基本函数' | '分式函数' | '指数对数' | '三角函数' | '反三角函数' | '常考组合'

export interface GraphSegment {
  from: number
  to: number
  fn: (x: number) => number
}

export interface GraphPoint {
  x: number
  y: number
  label?: string
}

export interface FunctionGraph {
  id: string
  title: string
  formula: string
  category: GraphCategory
  aliases: string
  domain: string
  range: string
  conclusion: string
  xRange: [number, number]
  yRange: [number, number]
  segments: GraphSegment[]
  verticalAsymptotes?: number[]
  horizontalAsymptotes?: number[]
  points?: GraphPoint[]
}

const segment = (from: number, to: number, fn: (x: number) => number): GraphSegment => ({ from, to, fn })

export const graphCategories: GraphCategory[] = ['基本函数', '分式函数', '指数对数', '三角函数', '反三角函数', '常考组合']

export const functionGraphs: FunctionGraph[] = [
  {
    id: 'linear',
    title: '一次函数',
    formula: 'y = x',
    category: '基本函数',
    aliases: '正比例 直线 奇函数',
    domain: 'ℝ',
    range: 'ℝ',
    conclusion: '奇函数，在 ℝ 上单调递增。',
    xRange: [-4, 4],
    yRange: [-4, 4],
    segments: [segment(-4, 4, (x) => x)],
    points: [{ x: 0, y: 0, label: 'O' }],
  },
  {
    id: 'quadratic',
    title: '二次函数',
    formula: 'y = x²',
    category: '基本函数',
    aliases: '抛物线 偶函数',
    domain: 'ℝ',
    range: '[0,+∞)',
    conclusion: '偶函数；在负半轴递减，在正半轴递增。',
    xRange: [-3, 3],
    yRange: [-1, 7],
    segments: [segment(-2.7, 2.7, (x) => x * x)],
    points: [{ x: 0, y: 0, label: 'O' }],
  },
  {
    id: 'cubic',
    title: '三次函数',
    formula: 'y = x³',
    category: '基本函数',
    aliases: '立方 奇函数 拐点',
    domain: 'ℝ',
    range: 'ℝ',
    conclusion: '奇函数，在 ℝ 上单调递增，原点是拐点。',
    xRange: [-2.3, 2.3],
    yRange: [-8, 8],
    segments: [segment(-2, 2, (x) => x ** 3)],
    points: [{ x: 0, y: 0, label: 'O' }],
  },
  {
    id: 'absolute',
    title: '绝对值函数',
    formula: 'y = |x|',
    category: '基本函数',
    aliases: '绝对值 偶函数 折点',
    domain: 'ℝ',
    range: '[0,+∞)',
    conclusion: '偶函数；x=0 处连续但不可导。',
    xRange: [-4, 4],
    yRange: [-1, 4],
    segments: [segment(-4, 4, (x) => Math.abs(x))],
    points: [{ x: 0, y: 0, label: 'O' }],
  },
  {
    id: 'square-root',
    title: '平方根函数',
    formula: 'y = √x',
    category: '基本函数',
    aliases: '根式 二分之一次幂',
    domain: '[0,+∞)',
    range: '[0,+∞)',
    conclusion: '单调递增，图像向下弯。',
    xRange: [-1, 6],
    yRange: [-0.6, 2.8],
    segments: [segment(0, 6, (x) => Math.sqrt(x))],
    points: [{ x: 0, y: 0, label: 'O' }, { x: 1, y: 1, label: '(1,1)' }],
  },
  {
    id: 'reciprocal',
    title: '反比例函数',
    formula: 'y = 1/x',
    category: '分式函数',
    aliases: '双曲线 倒数 奇函数',
    domain: 'ℝ∖{0}',
    range: 'ℝ∖{0}',
    conclusion: '奇函数；x=0、y=0 是渐近线。',
    xRange: [-4, 4],
    yRange: [-4, 4],
    segments: [segment(-4, -0.18, (x) => 1 / x), segment(0.18, 4, (x) => 1 / x)],
    verticalAsymptotes: [0],
    horizontalAsymptotes: [0],
    points: [{ x: 1, y: 1, label: '(1,1)' }, { x: -1, y: -1, label: '(-1,-1)' }],
  },
  {
    id: 'reciprocal-square',
    title: '平方反比例函数',
    formula: 'y = 1/x²',
    category: '分式函数',
    aliases: '倒数平方 偶函数',
    domain: 'ℝ∖{0}',
    range: '(0,+∞)',
    conclusion: '偶函数；x=0、y=0 是渐近线。',
    xRange: [-4, 4],
    yRange: [-0.6, 5],
    segments: [segment(-4, -0.18, (x) => 1 / x ** 2), segment(0.18, 4, (x) => 1 / x ** 2)],
    verticalAsymptotes: [0],
    horizontalAsymptotes: [0],
    points: [{ x: 1, y: 1, label: '(1,1)' }, { x: -1, y: 1, label: '(-1,1)' }],
  },
  {
    id: 'exponential',
    title: '自然指数函数',
    formula: 'y = eˣ',
    category: '指数对数',
    aliases: '指数函数 exp',
    domain: 'ℝ',
    range: '(0,+∞)',
    conclusion: '恒正且单调递增；y=0 是水平渐近线。',
    xRange: [-3.5, 2.5],
    yRange: [-0.6, 7],
    segments: [segment(-3.5, 2, (x) => Math.exp(x))],
    horizontalAsymptotes: [0],
    points: [{ x: 0, y: 1, label: '(0,1)' }],
  },
  {
    id: 'negative-exponential',
    title: '衰减指数函数',
    formula: 'y = e⁻ˣ',
    category: '指数对数',
    aliases: '指数衰减',
    domain: 'ℝ',
    range: '(0,+∞)',
    conclusion: '恒正且单调递减；y=0 是水平渐近线。',
    xRange: [-2.5, 3.5],
    yRange: [-0.6, 7],
    segments: [segment(-2, 3.5, (x) => Math.exp(-x))],
    horizontalAsymptotes: [0],
    points: [{ x: 0, y: 1, label: '(0,1)' }],
  },
  {
    id: 'logarithm',
    title: '自然对数函数',
    formula: 'y = ln x',
    category: '指数对数',
    aliases: '对数函数 log',
    domain: '(0,+∞)',
    range: 'ℝ',
    conclusion: '单调递增，图像向下弯；x=0 是竖直渐近线。',
    xRange: [-1, 6],
    yRange: [-4, 2.5],
    segments: [segment(0.03, 6, (x) => Math.log(x))],
    verticalAsymptotes: [0],
    points: [{ x: 1, y: 0, label: '(1,0)' }],
  },
  {
    id: 'log-one-plus',
    title: '对数平移函数',
    formula: 'y = ln(1+x)',
    category: '指数对数',
    aliases: '对数平移 等价无穷小',
    domain: '(-1,+∞)',
    range: 'ℝ',
    conclusion: '单调递增；x=-1 是竖直渐近线，x→0 时与 x 等价。',
    xRange: [-1.5, 5],
    yRange: [-4, 2.5],
    segments: [segment(-0.97, 5, (x) => Math.log1p(x))],
    verticalAsymptotes: [-1],
    points: [{ x: 0, y: 0, label: 'O' }],
  },
  {
    id: 'sine',
    title: '正弦函数',
    formula: 'y = sin x',
    category: '三角函数',
    aliases: '正弦 周期 奇函数',
    domain: 'ℝ',
    range: '[-1,1]',
    conclusion: '奇函数，最小正周期为 2π。',
    xRange: [-2 * Math.PI, 2 * Math.PI],
    yRange: [-1.5, 1.5],
    segments: [segment(-2 * Math.PI, 2 * Math.PI, (x) => Math.sin(x))],
    points: [{ x: 0, y: 0, label: 'O' }, { x: Math.PI / 2, y: 1, label: 'π/2' }],
  },
  {
    id: 'cosine',
    title: '余弦函数',
    formula: 'y = cos x',
    category: '三角函数',
    aliases: '余弦 周期 偶函数',
    domain: 'ℝ',
    range: '[-1,1]',
    conclusion: '偶函数，最小正周期为 2π。',
    xRange: [-2 * Math.PI, 2 * Math.PI],
    yRange: [-1.5, 1.5],
    segments: [segment(-2 * Math.PI, 2 * Math.PI, (x) => Math.cos(x))],
    points: [{ x: 0, y: 1, label: '(0,1)' }, { x: Math.PI, y: -1, label: 'π' }],
  },
  {
    id: 'tangent',
    title: '正切函数',
    formula: 'y = tan x',
    category: '三角函数',
    aliases: '正切 周期 奇函数',
    domain: 'x ≠ π/2+kπ',
    range: 'ℝ',
    conclusion: '奇函数，最小正周期为 π；x=±π/2 是图中渐近线。',
    xRange: [-2, 2],
    yRange: [-4, 4],
    segments: [segment(-Math.PI / 2 + 0.04, Math.PI / 2 - 0.04, (x) => Math.tan(x))],
    verticalAsymptotes: [-Math.PI / 2, Math.PI / 2],
    points: [{ x: 0, y: 0, label: 'O' }],
  },
  {
    id: 'arcsine',
    title: '反正弦函数',
    formula: 'y = arcsin x',
    category: '反三角函数',
    aliases: '反正弦',
    domain: '[-1,1]',
    range: '[-π/2,π/2]',
    conclusion: '奇函数，在定义域上单调递增。',
    xRange: [-1.5, 1.5],
    yRange: [-2, 2],
    segments: [segment(-1, 1, (x) => Math.asin(x))],
    points: [{ x: 0, y: 0, label: 'O' }],
  },
  {
    id: 'arccosine',
    title: '反余弦函数',
    formula: 'y = arccos x',
    category: '反三角函数',
    aliases: '反余弦',
    domain: '[-1,1]',
    range: '[0,π]',
    conclusion: '在定义域上单调递减，arccos(-x)=π-arccos x。',
    xRange: [-1.5, 1.5],
    yRange: [-0.5, 3.7],
    segments: [segment(-1, 1, (x) => Math.acos(x))],
    points: [{ x: 0, y: Math.PI / 2, label: '(0,π/2)' }],
  },
  {
    id: 'arctangent',
    title: '反正切函数',
    formula: 'y = arctan x',
    category: '反三角函数',
    aliases: '反正切',
    domain: 'ℝ',
    range: '(-π/2,π/2)',
    conclusion: '奇函数且单调递增；y=±π/2 是水平渐近线。',
    xRange: [-6, 6],
    yRange: [-2, 2],
    segments: [segment(-6, 6, (x) => Math.atan(x))],
    horizontalAsymptotes: [-Math.PI / 2, Math.PI / 2],
    points: [{ x: 0, y: 0, label: 'O' }],
  },
  {
    id: 'x-exp-minus-x',
    title: '指数乘积函数',
    formula: 'y = xe⁻ˣ',
    category: '常考组合',
    aliases: '指数乘积 极值',
    domain: 'ℝ',
    range: '(-∞,1/e]',
    conclusion: 'x=1 时取最大值 1/e；x→+∞ 时趋于 0。',
    xRange: [-1.5, 6],
    yRange: [-4, 1],
    segments: [segment(-1.3, 6, (x) => x * Math.exp(-x))],
    horizontalAsymptotes: [0],
    points: [{ x: 0, y: 0, label: 'O' }, { x: 1, y: 1 / Math.E, label: '(1,1/e)' }],
  },
  {
    id: 'log-over-x',
    title: '对数商函数',
    formula: 'y = (ln x)/x',
    category: '常考组合',
    aliases: '对数除以x 极值',
    domain: '(0,+∞)',
    range: '(-∞,1/e]',
    conclusion: 'x=e 时取最大值 1/e；x→+∞ 时趋于 0。',
    xRange: [-0.6, 7],
    yRange: [-4, 1],
    segments: [segment(0.04, 7, (x) => Math.log(x) / x)],
    verticalAsymptotes: [0],
    horizontalAsymptotes: [0],
    points: [{ x: 1, y: 0, label: '(1,0)' }, { x: Math.E, y: 1 / Math.E, label: '(e,1/e)' }],
  },
  {
    id: 'x-power-x',
    title: '幂指函数',
    formula: 'y = xˣ',
    category: '常考组合',
    aliases: '幂指函数 对数求导 极值',
    domain: '(0,+∞)',
    range: '[e⁻¹ᐟᵉ,+∞)',
    conclusion: 'x=1/e 时取最小值 e⁻¹ᐟᵉ，对数求导最方便。',
    xRange: [-0.5, 3],
    yRange: [-0.2, 5],
    segments: [segment(0.015, 2.25, (x) => x ** x)],
    points: [{ x: 1 / Math.E, y: Math.exp(-1 / Math.E), label: 'x=1/e' }, { x: 1, y: 1, label: '(1,1)' }],
  },
]
